feat: create a custom input
WitchImage/sirap-frontend pull request #12
Opened 2023-05-23 20:15 UTC by juanF18

- Se crea el custom input con los props para enviar el placeholder, label y un id

2023-05-23 20:16 UTC, juanF18 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear componente para Input](https://trello.com/c/tpQRxBt3/53-crear-componente-para-input)

2023-05-23 23:12 UTC, WitchImage requested changes

2023-05-23 23:12 UTC, WitchImage commented on src/components/input.tsx
> +                className='bg-darkGray
El Input debe tener el `border-blue-700`  cuando está `focus`. En el ejemplo aparece el border de color blanco.

2023-05-25 14:20 UTC, juanF18 commented on src/components/input.tsx
> +    placeholder: string;
Listo

2023-05-25 16:40 UTC, WitchImage requested changes

2023-05-25 16:40 UTC, WitchImage commented on src/components/input.tsx
> +    value?: string;
Cambiar la propiedad `value` a obligatoria.

2023-05-25 16:40 UTC, WitchImage commented on src/components/input.tsx
> +                required
Agregar `value` al input que es el mismo value que se pasa por props.

2023-05-30 15:58 UTC, juanF18 commented on src/components/input.tsx
> +    value?: string;
Resuelto en el ultimo commit

2023-05-30 15:58 UTC, juanF18 commented on src/components/input.tsx
> +                border border-white
Se borro la propiedad de `border-white`

2023-06-09 20:23 UTC, merged