feat: add custom card
WitchImage/sirap-frontend pull request #6
Opened 2023-04-22 03:49 UTC by juanF18

Se crea la custom card y se le puede pasar cualquier hijo para poder ser reutilizada.

2023-04-22 03:49 UTC, juanF18 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear componente genérico para Card](https://trello.com/c/1yRzYxh9/56-crear-componente-gen%C3%A9rico-para-card)

2023-04-24 01:42 UTC, WitchImage requested changes

2023-04-24 01:42 UTC, WitchImage commented on src/components/Card.tsx
> +    width: string;
renombrar width a className

2023-04-24 01:42 UTC, WitchImage commented on src/components/Card.tsx
> +        <div className={`m-2 h-50 ${width} p-4  rounded-lg bg-backgroundDark`}>
Eliminar m-2 y h-50 y reemplazar width por la nueva prop className

2023-04-24 02:05 UTC, WitchImage requested changes

2023-04-24 02:05 UTC, WitchImage commented on src/components/Card.tsx
> +    console.log(width);
Eliminar console.log

2023-04-24 03:02 UTC, juanF18 commented on src/components/Card.tsx
> +    width: string;
Se soluciono en el ultimo commit

2023-04-24 03:02 UTC, juanF18 commented on src/components/Card.tsx
> +        <div className={`m-2 h-50 ${width} p-4  rounded-lg bg-backgroundDark`}>
Se elimino en el ultimo commit

2023-04-24 03:03 UTC, juanF18 commented on src/components/Card.tsx
> +    console.log(width);
Se elimino en el ultimo commit

2023-04-25 15:30 UTC, merged